import type { Language } from "./types";

/**
 * Target content languages, taken verbatim from YouTube's own "add language"
 * localization picker (the codes YouTube itself offers). This is broader than
 * the UI `i18nLanguages` set. The main process uploads adaptively: it tries the
 * full selection and, only if YouTube rejects it, drops the specific codes it
 * won't accept (see electron/youtube.ts) — so the picker can safely list
 * everything YouTube shows without risking a failed upload.
 *
 * `nativeName` mirrors `name` (the UI only renders `name`); kept for the type.
 */
const L = (code: string, name: string): Language => ({ code, name, nativeName: name });

export const LANGUAGES: Language[] = [
  L("ab", "Abkhazian"),
  L("aa", "Afar"),
  L("af", "Afrikaans"),
  L("ak", "Akan"),
  L("akk", "Akkadian"),
  L("sq", "Albanian"),
  L("ase", "American Sign Language"),
  L("am", "Amharic"),
  L("ar", "Arabic"),
  L("arc", "Aramaic"),
  L("hy", "Armenian"),
  L("frp", "Arpitan"),
  L("as", "Assamese"),
  L("ay", "Aymara"),
  L("az", "Azerbaijani"),
  L("bm", "Bambara"),
  L("bn", "Bangla"),
  L("bn-IN", "Bangla (India)"),
  L("ba", "Bashkir"),
  L("eu", "Basque"),
  L("be", "Belarusian"),
  L("bh", "Bhojpuri"),
  L("bi", "Bislama"),
  L("brx", "Bodo"),
  L("bs", "Bosnian"),
  L("br", "Breton"),
  L("bg", "Bulgarian"),
  L("my", "Burmese"),
  L("yue", "Cantonese"),
  L("yue-HK", "Cantonese (Hong Kong)"),
  L("ca", "Catalan"),
  L("chr", "Cherokee"),
  L("zh", "Chinese"),
  L("zh-CN", "Chinese (China)"),
  L("zh-HK", "Chinese (Hong Kong)"),
  L("zh-Hans", "Chinese (Simplified)"),
  L("zh-SG", "Chinese (Singapore)"),
  L("zh-TW", "Chinese (Taiwan)"),
  L("zh-Hant", "Chinese (Traditional)"),
  L("cho", "Choctaw"),
  L("cop", "Coptic"),
  L("co", "Corsican"),
  L("cr", "Cree"),
  L("hr", "Croatian"),
  L("cs", "Czech"),
  L("da", "Danish"),
  L("doi", "Dogri"),
  L("nl", "Dutch"),
  L("nl-BE", "Dutch (Belgium)"),
  L("nl-NL", "Dutch (Netherlands)"),
  L("dz", "Dzongkha"),
  L("en", "English"),
  L("en-AU", "English (Australia)"),
  L("en-CA", "English (Canada)"),
  L("en-IN", "English (India)"),
  L("en-IE", "English (Ireland)"),
  L("en-GB", "English (United Kingdom)"),
  L("en-US", "English (United States)"),
  L("eo", "Esperanto"),
  L("et", "Estonian"),
  L("ee", "Ewe"),
  L("fo", "Faroese"),
  L("fj", "Fijian"),
  L("fil", "Filipino"),
  L("fi", "Finnish"),
  L("fr", "French"),
  L("fr-BE", "French (Belgium)"),
  L("fr-CA", "French (Canada)"),
  L("fr-FR", "French (France)"),
  L("fr-CH", "French (Switzerland)"),
  L("ff", "Fula"),
  L("gl", "Galician"),
  L("lg", "Ganda"),
  L("ka", "Georgian"),
  L("de", "German"),
  L("de-AT", "German (Austria)"),
  L("de-DE", "German (Germany)"),
  L("de-CH", "German (Switzerland)"),
  L("el", "Greek"),
  L("gn", "Guarani"),
  L("gu", "Gujarati"),
  L("guz", "Gusii"),
  L("ht", "Haitian Creole"),
  L("hak", "Hakka Chinese"),
  L("hak-TW", "Hakka Chinese (Taiwan)"),
  L("bgc", "Haryanvi"),
  L("ha", "Hausa"),
  L("haw", "Hawaiian"),
  L("iw", "Hebrew"),
  L("hi", "Hindi"),
  L("hi-Latn", "Hindi (Latin)"),
  L("ho", "Hiri Motu"),
  L("hu", "Hungarian"),
  L("is", "Icelandic"),
  L("ig", "Igbo"),
  L("id", "Indonesian"),
  L("ia", "Interlingua"),
  L("ie", "Interlingue"),
  L("iu", "Inuktitut"),
  L("ik", "Inupiaq"),
  L("ga", "Irish"),
  L("it", "Italian"),
  L("ja", "Japanese"),
  L("jv", "Javanese"),
  L("kl", "Kalaallisut"),
  L("kln", "Kalenjin"),
  L("kam", "Kamba"),
  L("kn", "Kannada"),
  L("ks", "Kashmiri"),
  L("kk", "Kazakh"),
  L("km", "Khmer"),
  L("ki", "Kikuyu"),
  L("rw", "Kinyarwanda"),
  L("tlh", "Klingon"),
  L("kok", "Konkani"),
  L("ko", "Korean"),
  L("ku", "Kurdish"),
  L("ky", "Kyrgyz"),
  L("lad", "Ladino"),
  L("lo", "Lao"),
  L("la", "Latin"),
  L("lv", "Latvian"),
  L("ln", "Lingala"),
  L("lt", "Lithuanian"),
  L("jbo", "Lojban"),
  L("dsb", "Lower Sorbian"),
  L("lu", "Luba-Katanga"),
  L("luo", "Luo"),
  L("lb", "Luxembourgish"),
  L("luy", "Luyia"),
  L("mk", "Macedonian"),
  L("mai", "Maithili"),
  L("mg", "Malagasy"),
  L("ms", "Malay"),
  L("ms-SG", "Malay (Singapore)"),
  L("ml", "Malayalam"),
  L("mt", "Maltese"),
  L("mni", "Manipuri"),
  L("mi", "Māori"),
  L("mr", "Marathi"),
  L("mas", "Masai"),
  L("mer", "Meru"),
  L("nan", "Min Nan Chinese"),
  L("nan-TW", "Min Nan Chinese (Taiwan)"),
  L("mxp", "Mixe"),
  L("lus", "Mizo"),
  L("mn", "Mongolian"),
  L("mn-Mong", "Mongolian (Mongolian)"),
  L("na", "Nauru"),
  L("nv", "Navajo"),
  L("ne", "Nepali"),
  L("pcm", "Nigerian Pidgin"),
  L("nd", "North Ndebele"),
  L("nso", "Northern Sotho"),
  L("no", "Norwegian"),
  L("oc", "Occitan"),
  L("or", "Odia"),
  L("om", "Oromo"),
  L("pap", "Papiamento"),
  L("ps", "Pashto"),
  L("fa", "Persian"),
  L("fa-AF", "Persian (Afghanistan)"),
  L("fa-IR", "Persian (Iran)"),
  L("pl", "Polish"),
  L("pt", "Portuguese"),
  L("pt-BR", "Portuguese (Brazil)"),
  L("pt-PT", "Portuguese (Portugal)"),
  L("pa", "Punjabi"),
  L("qu", "Quechua"),
  L("ro", "Romanian"),
  L("mo", "Romanian (Moldova)"),
  L("rm", "Romansh"),
  L("rn", "Rundi"),
  L("ru", "Russian"),
  L("ru-Latn", "Russian (Latin)"),
  L("sm", "Samoan"),
  L("sg", "Sango"),
  L("sa", "Sanskrit"),
  L("sat", "Santali"),
  L("sc", "Sardinian"),
  L("gd", "Scottish Gaelic"),
  L("sr", "Serbian"),
  L("sr-Cyrl", "Serbian (Cyrillic)"),
  L("sr-Latn", "Serbian (Latin)"),
  L("sh", "Serbo-Croatian"),
  L("sdp", "Sherdukpen"),
  L("sn", "Shona"),
  L("scn", "Sicilian"),
  L("sd", "Sindhi"),
  L("si", "Sinhala"),
  L("sk", "Slovak"),
  L("sl", "Slovenian"),
  L("so", "Somali"),
  L("nr", "South Ndebele"),
  L("st", "Southern Sotho"),
  L("es", "Spanish"),
  L("es-419", "Spanish (Latin America)"),
  L("es-MX", "Spanish (Mexico)"),
  L("es-ES", "Spanish (Spain)"),
  L("es-US", "Spanish (United States)"),
  L("su", "Sundanese"),
  L("sw", "Swahili"),
  L("ss", "Swati"),
  L("sv", "Swedish"),
  L("tl", "Tagalog"),
  L("tg", "Tajik"),
  L("ta", "Tamil"),
  L("tt", "Tatar"),
  L("te", "Telugu"),
  L("th", "Thai"),
  L("bo", "Tibetan"),
  L("ti", "Tigrinya"),
  L("tpi", "Tok Pisin"),
  L("tok", "Toki Pona"),
  L("to", "Tongan"),
  L("ts", "Tsonga"),
  L("tn", "Tswana"),
  L("tr", "Turkish"),
  L("tk", "Turkmen"),
  L("tw", "Twi"),
  L("uk", "Ukrainian"),
  L("hsb", "Upper Sorbian"),
  L("ur", "Urdu"),
  L("ug", "Uyghur"),
  L("uz", "Uzbek"),
  L("ve", "Venda"),
  L("vi", "Vietnamese"),
  L("vo", "Volapük"),
  L("vro", "Võro"),
  L("wa", "Walloon"),
  L("cy", "Welsh"),
  L("fy", "Western Frisian"),
  L("wal", "Wolaytta"),
  L("wo", "Wolof"),
  L("xh", "Xhosa"),
  L("yi", "Yiddish"),
  L("yo", "Yoruba"),
  L("zu", "Zulu"),
];

/**
 * Default target-language preset, loaded by the "Load default" button. These
 * are the languages marked in the reference setup; every code exists in
 * LANGUAGES above. Edit this list to change the default selection.
 */
export const DEFAULT_TARGET_LANGUAGES: string[] = [
  "az", "sq", "am", "en", "ar", "hy", "eu", "be", "bg", "bs",
  "cy", "hu", "vi", "haw", "gl", "el", "ka", "da", "iw", "id",
  "ga", "is", "es", "es-ES", "it", "yue", "yue-HK", "ca", "zh", "zh-Hans",
  "ko", "co", "lv", "lt", "lb", "mk", "ml", "mt", "mi", "mn",
  "de", "de-DE", "nl", "no", "pl", "pt", "pt-PT", "ro", "sr", "sr-Cyrl",
  "sr-Latn", "sk", "sl", "tr", "tk", "uz", "uk", "ur", "fil", "fi",
  "fr", "hi", "hr", "cs", "sv", "et", "ja",
];

export const UI_LANGUAGES = [
  { code: "en", label: "English", flag: "🇬🇧" },
  { code: "de", label: "Deutsch", flag: "🇩🇪" },
  { code: "fr", label: "Français", flag: "🇫🇷" },
  { code: "uk", label: "Українська", flag: "🇺🇦" },
  { code: "ru", label: "Русский", flag: "🇷🇺" },
] as const;

export type UILanguageCode = (typeof UI_LANGUAGES)[number]["code"];

export function findLanguage(code: string): Language | undefined {
  return LANGUAGES.find((l) => l.code === code);
}
